### PR TITLE
Allow `delta_options` request option for updating data sources

### PR DESCRIPTION
**Pull request by joshhk72**

### CODE REVIEW

**Comment by joshhk72** [comment]
Ah shoot were there other Stardog changes since https://github.com/stardog-union/stardog.js/pull/300 ?

**Comment by anneeb** [comment]
> Ah shoot were there other Stardog changes since #300 ?

**Comment by joshhk72** [comment]
Something about `icv.violations` changed that it's not accepting the current Accept header (`*/*`) we're sending, but changing it also doesn't seem to work. Checking in with Platform team, but abandoning for a bit.

**Comment by joshhk72** [comment]
Idk what's going on with the `listUserRoles` and `listRoleUsers` tests failing (they work for me locally)

**Comment by joshhk72** [comment]
Ohhh... I see

https://stardog.atlassian.net/browse/PLAT-1520

**Review by anneeb — APPROVED** [review]

**Pull request merged**
