### PR TITLE
Fix capitalization for mimetype in docs

### PR DESCRIPTION
**Pull request by joshhk72**

### CODE REVIEW

**Comment by jmrog** [comment]
@joshhk72 I don't think this is right. The (lack of) capitalization seems correct, based on the implementation here: https://github.com/stardog-union/stardog.js/blob/master/lib/db/main.js#L213

**Comment by joshhk72** [comment]
@jmrog this is removing the capitalization, since it's `mimeType` in the docs.

**Comment by jmrog** [comment]
> @jmrog this is removing the capitalization, since it's `mimeType` in the docs.

Oh, 🤦 . I read it in reverse.

**Review by jmrog — APPROVED** [review]
LGTM

**Pull request merged**
