### PR TITLE
[VET-1472] Implement new data source query API in stardog.js

### PR DESCRIPTION
**Pull request by SpiralP**
VET-1472

* added `query` data-source method
* added other (missing) data-source methods as well:
  * refreshCounts
  * refreshMetadata

### CODE REVIEW

**Comment by SpiralP** [comment]
since ci doesn't have a mysql server to test, i tested locally with:
```js
Stardog.dataSources
  .query(
    new Stardog.Connection({
      endpoint: 'http://localhost:5820',
      username: 'admin',
      password: 'admin',
    }),
    'mysql',
    'select * from employees limit 10'
  )
  .then(({body}) => console.log(body), console.log);
```
<details>
  <summary>Click to expand!</summary>
 
```js
{
  mColumns: {
    '0': { mName: 'emp_no', mType: 'INT', mSize: 10 },
    '1': { mName: 'birth_date', mType: 'DATE', mSize: 10 },
    '2': { mName: 'first_name', mType: 'VARCHAR', mSize: 14 },
    '3': { mName: 'last_name', mType: 'VARCHAR', mSize: 16 },
    '4': { mName: 'gender', mType: 'CHAR', mSize: 1 },
    '5': { mName: 'hire_date', mType: 'DATE', mSize: 10 }
  },
  mRows: {
    '0': {
      '0': '10001',
      '1': '1953-09-02',
      '2': 'Georgi',
      '3': 'Facello',
      '4': 'M',
      '5': '1986-06-26'
    },
    '1': {
      '0': '10002',
      '1': '1964-06-02',
      '2': 'Bezalel',
      '3': 'Simmel',
      '4': 'F',
      '5': '1985-11-21'
    },
    '2': {
      '0': '10003',
      '1': '1959-12-03',
      '2': 'Parto',
      '3': 'Bamford',
      '4': 'M',
      '5': '1986-08-28'
    },
    '3': {
      '0': '10004',
      '1': '1954-05-01',
      '2': 'Chirstian',
      '3': 'Koblick',
      '4': 'M',
      '5': '1986-12-01'
    },
    '4': {
      '0': '10005',
      '1': '1955-01-21',
      '2': 'Kyoichi',
      '3': 'Maliniak',
      '4': 'M',
      '5': '1989-09-12'
    },
    '5': {
      '0': '10006',
      '1': '1953-04-20',
      '2': 'Anneke',
      '3': 'Preusig',
      '4': 'F',
      '5': '1989-06-02'
    },
    '6': {
      '0': '10007',
      '1': '1957-05-23',
      '2': 'Tzvetan',
      '3': 'Zielinski',
      '4': 'F',
      '5': '1989-02-10'
    },
    '7': {
      '0': '10008',
      '1': '1958-02-19',
      '2': 'Saniya',
      '3': 'Kalloufi',
      '4': 'M',
      '5': '1994-09-15'
    },
    '8': {
      '0': '10009',
      '1': '1952-04-19',
      '2': 'Sumant',
      '3': 'Peac',
      '4': 'F',
      '5': '1985-02-18'
    },
    '9': {
      '0': '10010',
      '1': '1963-06-01',
      '2': 'Duangkaew',
      '3': 'Piveteau',
      '4': 'F',
      '5': '1989-08-24'
    }
  }
}
```

</details>

**Comment by anneeb** [comment]
you'll also want to add docs to `index.d.ts` and then run `npm run docs` to update the readme

**Comment by jmrog** [comment]
Good work, everyone!

**Review by anneeb — APPROVED** [review]
LGTM!

**Review by joshhk72 — APPROVED** [review]
LGTM!

**Pull request merged**
